config/routes.rb
HoppApp::Application.routes.draw do
  root :to => 'pages#home'

  get '/home' => 'pages#home2'
  get '/user/login' => 'session#new'
  post '/user/login' => 'session#create'
  delete '/user/login' => 'session#destroy', :as => 'logout'
  get '/begin' => 'pages#begin'
  get '/end' => 'pages#end'
  get '/bookmarks' => 'bookmarks#show'
  post '/bookmarks' => 'bookmarks#create'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/demo' => 'pages#demo'

  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :interests, :except => [:show, :edit] do
    collection do
      get 'edit'
    end
  end

  resources :content

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
	has_secure_password
	attr_accessible :name, :email, :password, :password_confirmation
	has_and_belongs_to_many :interests, :uniq => true
	has_many :bookmarks
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_if_logged_in, :except =>[:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]

    if @user.save
      session[:user_id] = @user.id
      #NotificationMailer.notification_email(@user.email).deliver

      # new path to set user interests
      redirect_to new_interest_path

    else
      render :new
    end
  end

  def edit
    #where do we get @current_user from?
    @user = @current_user
    render "edit"
  end

  def update
    @user = @current_user
    if @user.update_attributes params[:user]
      redirect_to root_path
    else
      render "new"
    end
  end



end

app/views/users/edit.html.haml
%div.sign

  = link_to 'Edit Your Interests', edit_interests_path, {:class => 'button_right chat'}
  %h1= "Change Password"
  = form_for @user do |f|
    %div
      =f.label :name
      =f.text_field :name, :autofocus => true
    %div
      =f.label :email
      =f.text_field :email
    %div
      =f.label :password
      =f.password_field :password
    %div
      =f.label :password_confirmation
      =f.password_field :password_confirmation
    =f.submit 'Submit'

app/views/users/new.html.haml
- if @user.errors.any?
  %ul.list-unstyled
    %li.alert.alert-danger Did your Passwords match?

%div.sign

  %h2= "Create a User Account"

  = form_for @user do |f|
    %div
      =f.label :name
      =f.text_field :name, :autofocus => true
    %div
      =f.label :email
      =f.text_field :email
    %div
      =f.label :password
      =f.password_field :password
    %div
      =f.label :password_confirmation
      =f.password_field :password_confirmation, :class => 'form-control'
    =f.submit 'Sign Up'