config/routes.rb
HoppApp::Application.routes.draw do
  root :to => 'pages#home'

  get '/home' => 'pages#home2'
  get '/user/login' => 'session#new'
  post '/user/login' => 'session#create'
  delete '/user/login' => 'session#destroy', :as => 'logout'
  get '/begin' => 'pages#begin'
  get '/end' => 'pages#end'
  get '/bookmarks' => 'bookmarks#show'
  post '/bookmarks' => 'bookmarks#create'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/demo' => 'pages#demo'

  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :interests, :except => [:show, :edit] do
    collection do
      get 'edit'
    end
  end

  resources :content

end

app/views/pages/about.html.erb
<h1> About Hopp </h1>

<div class="about">


  <p> Have you ever noticed how you can lose yourself in endless recommendations and external links on the internet, or how you end up losing track of time or spend more time than you originally planned on your favorite sites?</p>

  <p> Hopp is the fix to all of your problems when it comes to procrastinating on the internet.</p>

  <p> We take in your interests once <span class="small-text">(don't worry you can edit these at any time)</span>, and give you content <span class="strong">relevant to you</span>, all from your favorite sources. The best part is, we do it all based on how much time you have to spend each time you visit the site.</p>

  <p> Hopp is perfect for a break from your work, or to fill your commute with time appropriate content. </p>

  <p><span class="strong"> Hopp. Fill your time with the stuff you love.</span></p>

  <p><a href="/"><< Back to Home</a></p>

</div>

app/views/pages/begin.html.erb
<div class="container sign">
  <h1>How long have you got?</h1>

  <label for="mydate"></label>

  <input name="mydate" id="mydate" type="date" data-role="datebox" placeholder="Click to enter your allotted time.."
     data-options='{"mode": "durationbox", "overrideDurationFormat": "%DM:%DS", "useFocus": true, "useButton": false, "overrideTitleDateDialogLabel": "Hopp Timer"}'>

</div>

app/views/pages/contact.html.erb
<h1> Contact </h1>

<div class="no-text-shadow">

  <p class="big"> Find us on... </p>

  <a class="social" href="https://www.facebook.com/hoppappsydney" target="_blank">
    <div class="social-link-circle">
      <i class="fa fa-facebook"></i>
    </div>
  </a>

  <a class="social" href="https://twitter.com/hopp_app" target="_blank">
    <div class="social-link-circle">
      <i class="fa fa-twitter"></i>
    </div>
  </a>


<!--     <div class="social-link-circle">
      <i class="fa fa-linkedin"></i>
    </div> -->


  <p>Hopp was made by:</p>

  <p>Nick Doherty
    <a href="mailto:nickdoherty@gmail.com"><i class="fa fa-envelope"></i></a>
    <a href="http://www.linkedin.com/profile/view?id=22024237&locale=en_US&trk=tyah&trkInfo=tas%3Anick%2Cidx%3A3-1-3" target="_blank"><i class="fa fa-linkedin-square"></i></a>
  </p>

  <p>Matt Thees
    <a href="mailto:mtt33@georgetown.edu"><i class="fa fa-envelope"></i></a>
    <a href="http://www.linkedin.com/profile/view?id=278183632&trk=nav_responsive_tab_profile" target="_blank"><i class="fa fa-linkedin-square"></i></a>
  </p>

  <p> Feel free to contact us with feedback or suggestions!</p>

  <br/>
  <br/>

   <p><a href="/"><< Back to Home</a></p>

  <div class="thanks">
    <p>Special thanks to:</p>
    <p>Joel Turnbull + Daniel Tsui</p>
  </div>

</div>

app/views/pages/demo.html.erb
<div class="whatever_content">

  <h2>This is sample content generated by random, preset interests for this demo.</h2>

  <% if @medium_content.present? %>
    <h3> via <a href="http://www.medium.com" target="_blank">Medium</a></h3>
    <div class="content_container">
      <%== @medium_content %>
    </div>
  <% end %>

  <%== @soundcloud_content if @soundcloud_content %>

  <%if @youtube_content.present? %>
    <div class="video_container">
      <%== @youtube_content if @youtube_content %>
    </div>
  <%end%>

  <div class="demo-link-a">
    <a class="demo-home demo" href="/">Back to Home</a>
  </div>

  <div class="demo-link-b">
    <a class="demo-hopp demo" href="javascript:history.go(0)">Hopp to new Content</a>
  </div>

  <div class="demo-sign-up">
    <a href="/users/new" class="demo">Sign Up</a>
    <p class="small">Signing up lets view content personalized for you based on your available time and interests.</p>
</div>

app/views/pages/end.html.erb
<h1>Your time is up!</h1>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.hoppto.it" data-text="I just used hopp! Fill your time with the stuff you love. Try it out:" data-via="hopp_app" data-size="large" data-hashtags="hopp">Tweet</a>
<a href="https://twitter.com/hopp_app" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @hopp_app</a>

app/views/pages/home.html.erb
<div class="home">
  <h1 class="logo-large">hopp</h1>

  <p class="home_text">Turbo-charge your morning commute. Take control of your study break. Super-size your lunch break. Fill your time with the stuff you love. Make every second count.</p>

  <%if @current_user.present? %>
    <%= button_to 'Hopp to it!', begin_path, :method => :get %>
  <% else %>
    <%= link_to 'Sign Up', new_user_path %>
    <%= link_to 'Login', user_login_path %>
    <h2> or.. </h2>
    <%= link_to 'Try it Out', demo_path, "class" => "demo-button" %>
  <% end %>

<script>
$(document).bind('pagechange', function () {
  if ($('.home').is(':visible')) {
    url = 'url(/assets/hopp_background.jpg)'
  } else {
    url = 'none'
  }
  $('body .ui-body-b').css({
    backgroundImage: url
  });
});
</script>

<style>
body .ui-body-b {
  background-position: 55% 35%;
  background-size: cover;
}
</style>

</div>

app/views/pages/home2.html.erb
<div class="home">
  <h1 class="logo-large">hopp</h1>

  <p class="home_text">Turbo-charge your morning commute. Take control of your study break. Super-size your lunch break. Fill your time with the stuff you love. Make every second count.</p>

  <%if @current_user.present? %>
    <%= button_to 'Hopp to it!', begin_path, :method => :get %>
  <% else %>
    <%= link_to 'Sign Up', new_user_path %>
    <%= link_to 'Login', user_login_path %>
    <h2> or.. </h2>
    <%= link_to 'Try it Out', demo_path, "class" => "demo-button" %>
  <% end %>

<script>
$(document).bind('pagechange', function () {
  if ($('.home').is(':visible')) {
    url = 'url(/assets/hopp_background.jpg)'
  } else {
    url = 'none'
  }
  $('body .ui-body-b').css({
    backgroundImage: url
  });
});
</script>

<style>
body .ui-body-b {
  background-position: 55% 35%;
  background-size: cover;
}
</style>

</div>