config/routes.rb
HoppApp::Application.routes.draw do
  root :to => 'pages#home'

  get '/home' => 'pages#home2'
  get '/user/login' => 'session#new'
  post '/user/login' => 'session#create'
  delete '/user/login' => 'session#destroy', :as => 'logout'
  get '/begin' => 'pages#begin'
  get '/end' => 'pages#end'
  get '/bookmarks' => 'bookmarks#show'
  post '/bookmarks' => 'bookmarks#create'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/demo' => 'pages#demo'

  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :interests, :except => [:show, :edit] do
    collection do
      get 'edit'
    end
  end

  resources :content

end

app/views/layouts/_googletracking.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45901778-1', 'hoppto.it');
  ga('send', 'pageview');
</script>

app/views/layouts/_navigation.html.erb
<div class="container">
<% if @current_user.present? %>
  <ul class="nav navbar-nav">
    <li><%= link_to('Home', home_path) %></li>
    <li><%= link_to('Edit Profile', edit_users_path) %></li>
    <li><%= link_to(@current_user.name + "'s" + ' Hoppmarks') %></li>
    <li><%= link_to('Logout ' + @current_user.name, logout_path) %></li>
  </ul>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>hopp</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
  <link rel="stylesheet" type="text/css" href="http://dev.jtsage.com/cdn/datebox/latest/jqm-datebox.min.css" />
  <link href='http://fonts.googleapis.com/css?family=Cabin:400,700|Oswald:400,700' rel='stylesheet' type='text/css'>


  <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>

  <script type="text/javascript" src="http://cdn.jtsage.com/datebox/latest/jqm-datebox.core.min.js"></script>
  <script type="text/javascript" src="http://cdn.jtsage.com/datebox/latest/jqm-datebox.mode.durationbox.min.js"></script>
  <script type="text/javascript" src="http://cdn.jtsage.com/datebox/i18n/jquery.mobile.datebox.i18n.en_US.utf8.js"></script>

  <link rel="stylesheet" href="path/to/add2home.css">
  <script type="application/javascript" src="path/to/add2home.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <div class="container">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="collapse navbar-collapse">
        <%= render 'layouts/navigation' %>
      </div><!--/.nav-collapse -->
    </div>

      <div>
        <%= yield %>
      </div>
      <div>
        <p class="minor"><a href="/contact">Contact</a> | <a href="/about">About</a> | Hopp &copy;2013</p>
      </div>
    </div>
  </div> <!-- container -->
  <% if Rails.env.production? %>
  <%= render :partial => 'layouts/googletracking' %>
  <%end%>
</body>
</html>